---
title: "Visualization"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(infer)
library(broom)
songs_complete <- read_csv("/cloud/project/data/SpotifyFeatures.csv")
```

```{r songs-less}

songs <- sample_n(songs_complete, 5000, replace = FALSE)

songs
```

### Relationship Between Different Variables and Song Popularity

```{r plot-genre-popularity, fig.width=15, fig.width=15}
ggplot(data = songs, mapping = aes(x = genre, y = popularity)) +
  geom_boxplot() +
  labs(title = "Genre v. Popularity of Songs", x = "Genre", y = "Popularity")
```

```{r plot-acousticness-popularity}
ggplot(data = songs, mapping = aes(x = acousticness, y = popularity, alpha = 0.005)) +
  geom_point() + 
  geom_smooth() +
  labs(title = "Acousticness v. Popularity of Songs", x = "Acousticness", y = "Popularity")
```


```{r plot-energy-popularity}
ggplot(data = songs, mapping = aes(x = energy, y = popularity, alpha = 0.0005)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Energy v. Popularity of Songs", x = "Energy", y = "Popularity")
```

```{r plot-danceability-popularity}
ggplot(data = songs, mapping = aes(x = danceability, y = popularity, alpha = 0.0005)) +
  geom_point() + 
  geom_smooth() +
  labs(title = "Danceability v. Popularity of Songs", x = "Danceability", y = "Popularity")
```

```{r plotg-duration-popularity}
ggplot(data = songs, mapping = aes(x = duration_ms, y = popularity, alpha = 0.0005)) +
  geom_point() + 
  geom_smooth() +
  labs(title = "Duration v. Popularity of Songs", x = "Duration", y = "Popularity")
```

```{r plot-instrumentalness-popularity}
ggplot(data = songs, mapping = aes(x = instrumentalness, y = popularity, alpha = 0.0005)) +
  geom_point() + 
  geom_smooth() +
  labs(title = "Instrumentalness v. Popularity of Songs", x = "Instrumentalness", y = "Popularity")
```


```{r plot-key-popularity}
ggplot(data = songs, mapping = aes(x = key, y = popularity)) +
  geom_boxplot() +
  labs(title = "Key v. Popularity of Songs", x = "Key", y = "Popularity")
```


```{r plot-liveness-popularity}
ggplot(data = songs, mapping = aes(x = liveness, y = popularity, alpha = 0.0005)) +
  geom_point() + 
  geom_smooth() +
  labs(title = "Liveness v. Popularity of Songs", x = "Liveness", y = "Popularity")
```

```{r plot-loudness-popularity}
ggplot(data = songs, mapping = aes(x = loudness, y = popularity, alpha = 0.0005)) +
  geom_point() + 
  geom_smooth() +
  labs(title = "Loudness v. Popularity of Songs", x = "Loudness", y = "Popularity")
```

```{r plot-mode-popularity}
ggplot(data = songs, mapping = aes(x = mode, y = popularity)) +
  geom_boxplot() +
  labs(title = "Mode v. Popularity of Songs", x = "Mode", y = "Popularity")
```

```{r plot-speechiness-popularity}
ggplot(data = songs, mapping = aes(x = speechiness, y = popularity, alpha = 0.0005)) +
  geom_point() + 
  geom_smooth() +
  labs(title = "Speechiness v. Popularity of Songs", x = "Speechiness", y = "Popularity")
```

```{r plot-tempo-popularity}
ggplot(data = songs, mapping = aes(x = tempo, y = popularity, alpha = 0.0005)) +
  geom_point() + 
  geom_smooth() +
  labs(title = "Tempo v. Popularity of Songs", x = "Tempo", y = "Popularity")
```

```{r timesignature-popularity}
ggplot(data = songs, mapping = aes(x = time_signature, y = popularity)) +
  geom_boxplot() +
  labs(title = "Time Signature v. Popularity of Songs", x = "Time Signature", y = "Popularity")
```


```{r plot-valence-popularity}
ggplot(data = songs, mapping = aes(x = valence, y = popularity, alpha = 0.0005)) +
  geom_point() + 
  geom_smooth() +
  labs(title = "Valence v. Popularity of Songs", x = "Valence", y = "Popularity")
```


